version: '3.8'
services: 
  bdd:
    image: postgres:14.1-alpine
    container_name: NetStream
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=db
    ports:
      - '9254:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./:/docker-entrypoint-initdb.d

volumes:
  db: 
    driver: local